services:
  # Message Broker
  rabbit-mq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - flho_network
  # Cache
  redis:
    image: redis:8.0-M02-alpine
    ports:
      - "6379:6379"
    networks:
      - flho_network

networks:
  flho_network:
    external: true
