services:
  # IDENTITY SERVICE DEFINITIONS

  # Service
  identity-service:
    build:  .
    restart: always
    depends_on:
      - identity-service-database
    ports: 
      - "4002:4000"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DB_DSN: ${DB_DSN}
  # Database
  identity-service-database:
    image: 'postgres:14.2'
    ports:
      - "5433:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PASSWORD: ${DB_PASSWORD} 
    volumes:
      - ./.docker/postgres/:/var/lib/postgresql/data/
      - ./.docker/db_setup.sh:/docker-entrypoint-initdb.d/init-db.sh
