services:
  # Service
  app:
    build:  .
    restart: always
    depends_on:
      - workflow-service-database
    ports: 
      - "4003:4000"
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env
  # Database
  workflow-service-database:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - workflow-service-db-data:/data/db
  # Date Explorer
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${DB_URI}
      ME_CONFIG_BASICAUTH: false

volumes:
  workflow-service-db-data:

